# Generated by Django 4.0.4 on 2022-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField(verbose_name='Data e hora do evento')),
                ('data_criacao', models.DateTimeField(verbose_name='Data de criação')),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
